[package]
name = "mechanic-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
alacritty_terminal.workspace = true
mechanic-core.workspace = true
mechanic-config.workspace = true
libc.workspace = true
serde.workspace = true
serde_json = "1"
signal-hook = "0.4"

[dev-dependencies]
tempfile = "3"
