[package]
name = "mechanic-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "mechanic"
path = "src/main.rs"

[dependencies]
alacritty_terminal.workspace = true
winit.workspace = true
pollster.workspace = true
crossbeam-channel.workspace = true
log.workspace = true
env_logger.workspace = true
mechanic-core.workspace = true
mechanic-renderer.workspace = true
mechanic-config.workspace = true
arboard.workspace = true
unicode-width = "0.2"
url = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSApplication", "NSButton", "NSCell", "NSControl", "NSEvent", "NSGraphics", "NSGraphicsContext", "NSMenu", "NSMenuItem", "NSPanel", "NSResponder", "NSSearchField", "NSText", "NSTextField", "NSTextView", "NSView", "NSWindow", "NSWorkspace"] }
objc2-foundation = { version = "0.3", default-features = false, features = ["std", "NSGeometry", "NSNotification", "NSObject", "NSString", "NSURL"] }

[dev-dependencies]
wgpu.workspace = true
